#[derive(Debug, PartialEq, Clone, Copy)]
pub(crate) struct Token {
    pub(crate) token_type: TokenType,
    pub(crate) numeric_value_1: f32,
    pub(crate) numeric_value_2: f32,
}

#[derive(Debug, PartialEq, Clone, Copy)]
pub(crate) enum TokenType {
    Y,
    Equal,
    Comma,

    _Pi,
    _E,
    NegPi,
    NegE,

    Sin,
    Cos,
    Tan,
    Asin,
    Acos,
    Atan,

    Med,
    /// Synthetic token: Marks end of median() parameters (generated by parser, not tokenizer)
    EndMed,

    Mode,
    /// Synthetic token: Marks end of mode() parameters (generated by parser, not tokenizer)
    EndMode,

    Max,
    /// Synthetic token: Marks end of max() parameters (generated by parser, not tokenizer)
    EndMax,

    Abs,
    Sqrt,

    Min,
    /// Synthetic token: Marks end of min() parameters (generated by parser, not tokenizer)
    EndMin,

    Ln,
    Log,

    Avg,
    /// Synthetic token: Marks end of avg() parameters (generated by parser, not tokenizer)
    EndAvg,

    Choice,
    /// Synthetic token: Marks end of choice() parameters (generated by parser, not tokenizer)
    EndChoice,

    OpenParen,
    CloseParen,

    Factorial,

    Star,
    Slash,
    Plus,
    Minus,
    Power,
    Modulo,
    Percent,

    Number,

    X,
    End,
}

impl TokenType {
    /// Returns true if this token starts parameter collection for a variadic function
    ///
    /// These tokens trigger the evaluator to enter parameter collection mode.
    pub fn is_variadic_function(&self) -> bool {
        matches!(
            self,
            TokenType::Avg
                | TokenType::Min
                | TokenType::Max
                | TokenType::Mode
                | TokenType::Med
                | TokenType::Choice
        )
    }
}

#[derive(Debug, PartialEq)]
pub(crate) enum ParamToken {
    None,
    Avg,
    Min,
    Max,
    Med,
    Mode,
    Choice,
}

impl ParamToken {
    /// Returns the corresponding End* TokenType for this parameter token
    ///
    /// # Panics
    /// Panics if called on ParamToken::None
    pub fn to_end_token_type(&self) -> TokenType {
        match self {
            ParamToken::Avg => TokenType::EndAvg,
            ParamToken::Min => TokenType::EndMin,
            ParamToken::Max => TokenType::EndMax,
            ParamToken::Mode => TokenType::EndMode,
            ParamToken::Med => TokenType::EndMed,
            ParamToken::Choice => TokenType::EndChoice,
            ParamToken::None => panic!("Cannot convert ParamToken::None to TokenType"),
        }
    }
}
