#[derive(Debug, PartialEq, Clone, Copy)]
pub(crate) struct Token {
    pub(crate) token_type: TokenType,
    pub(crate) numeric_value_1: f32,
    pub(crate) numeric_value_2: f32,
}

#[derive(Debug, PartialEq, Clone, Copy)]
pub(crate) enum TokenType {
    Y,
    Equal,
    Comma,

    _Pi,
    _E,

    Sin,
    Cos,
    Tan,
    Asin,
    Acos,
    Atan,
    Sinh,
    Cosh,
    Tanh,
    Sec,
    Csc,
    Cot,
    Deg,
    Rad,

    Atan2,
    /// Synthetic token: Marks end of atan2() parameters (generated by parser, not tokenizer)
    EndAtan2,

    Med,
    /// Synthetic token: Marks end of median() parameters (generated by parser, not tokenizer)
    EndMed,

    Mode,
    /// Synthetic token: Marks end of mode() parameters (generated by parser, not tokenizer)
    EndMode,

    Max,
    /// Synthetic token: Marks end of max() parameters (generated by parser, not tokenizer)
    EndMax,

    Abs,
    Sqrt,

    Min,
    /// Synthetic token: Marks end of min() parameters (generated by parser, not tokenizer)
    EndMin,

    Ln,
    Log,

    Avg,
    /// Synthetic token: Marks end of avg() parameters (generated by parser, not tokenizer)
    EndAvg,

    Choice,
    /// Synthetic token: Marks end of choice() parameters (generated by parser, not tokenizer)
    EndChoice,

    OpenParen,
    CloseParen,

    Factorial,

    Star,
    Slash,
    Plus,
    Minus,
    UnaryMinus, // Unary negation operator
    Power,
    Modulo,
    Percent,

    Number,

    X,
    End,

    Pipe,
}

impl TokenType {
    /// Returns true if this token starts parameter collection for a variadic function
    ///
    /// These tokens trigger the evaluator to enter parameter collection mode.
    pub fn is_variadic_function(&self) -> bool {
        matches!(
            self,
            TokenType::Avg
                | TokenType::Min
                | TokenType::Max
                | TokenType::Mode
                | TokenType::Med
                | TokenType::Choice
                | TokenType::Atan2
        )
    }

    /// Returns the corresponding End* TokenType for this variadic function token type
    pub fn to_end_token_type(self) -> TokenType {
        match self {
            TokenType::Avg => TokenType::EndAvg,
            TokenType::Min => TokenType::EndMin,
            TokenType::Max => TokenType::EndMax,
            TokenType::Mode => TokenType::EndMode,
            TokenType::Med => TokenType::EndMed,
            TokenType::Choice => TokenType::EndChoice,
            TokenType::Atan2 => TokenType::EndAtan2,
            _ => unreachable!(
                "to_end_token_type called on non-variadic token type: {:?}",
                self
            ),
        }
    }
}
